version: "3.3"

services:

    flask:
        build: ./api
        container_name: flask
        restart: always
        ports: 
            - "8080:8080"
            # apagar portas quando em prod
        depends_on:
            - postgres


    postgres:
        image: postgres:12-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=
            - TZ=GMT
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - 5432:5432
            # apagar portas quando em prod

            
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports: 
            - "80:80"
        depends_on:
            - flask

